language: perl
perl:
  - 5.18
  - 5.16
  - 5.14
  - 5.12
  - 5.10
install:
   - dzil authordeps --missing | cpanm -nq || { cat ~/.cpanm/build.log ; false ; }
   - dzil listdeps --author --missing | grep -v Baz | cpanm -nq || { cat ~/.cpanm/build.log ; false ; }
   - git config --local user.name Travis
   - git config --local user.email travis@localhost
script:
   - dzil test --automated --author --release
