---
abstract: 'convert Changes from YAML to CPAN::Changes::Spec format'
author:
  - 'Carlos Lima <carlos@cpan.org>'
build_requires:
  Test::DZil: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.130880'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-ChangesFromYaml
no_index:
  directory:
    - corpus
  file:
    - perlcritic.rc
requires:
  CPAN::Changes: 0
  Dist::Zilla::Role::FileMunger: 0
  Exporter: 0
  Moose: 0
  YAML::XS: 0
  namespace::autoclean: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/xenoterracide/dist-zilla-plugin-changesfromyaml/issues
  homepage: https://metacpan.org/dist/Dist-Zilla-Plugin-ChangesFromYaml
  repository: git://github.com/xenoterracide/dist-zilla-plugin-changesfromyaml.git
version: 0.001
